apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secrets-store-csi-driver-image-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
      - name: git_ref_type
        value: branches
      - name: git_version
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_version
      - name: git_ref_type
      - name: upstream_repo
        value: registry.k8s.io/csi-secrets-store/driver
      - name: upstream_tag
        value: v1.3.1
      - name: repo_name
        value: quay.io/bradfordwagner/secrets-store-csi-driver
    dag:
      tasks:
      - name: custom-dockerfile
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-secrets-store-csi-driver
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}"
          - name: tag_suffix # forms git_version-platform
            value: ""
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
          - name: platform
            value: ""
          - name: dockerfile
            value: |
              # image from: https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/build-image/debian-base
              FROM registry.k8s.io/build-image/debian-base:bullseye-v1.4.3
              COPY --from=builder /secrets-store-csi /secrets-store-csi
              RUN apt update && \
                apt upgrade -y && \
                clean-install ca-certificates mount
        templateRef:
          name: flavor-custom-dockerfile-template
          template: "{{ inputs.parameters.git_ref_type }}"
        withItems:
        - { runtime_platforms: [linux/amd64] }
